site_name: tapestry
theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - User Guide:
      - user-guide/index.md
      - Installation: user-guide/install.md
      - Getting started: user-guide/getting-started.md
      - Docker: user-guide/docker.md
  - Rationale: rationale.md


markdown_extensions:
  - admonition
  - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - include-markdown:
      preserve_includer_indent: true
